<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <title></title>
</head>
<body>


<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th align="center">CUMPLIMIENTO (%)</th>
      <th align="center">NO CUMPLIMIENTO (%)</th>
    </tr>
  </thead>
  <tbody>
    <tr class="clickable" data-toggle="collapse" data-target="#group-of-rows-1">
      <td><i class="fa fa-plus" aria-hidden="true"></i></td>
      <td align="center">COCINAS A GAS</td>
      <td align="center">63.97</td>
      <td align="center">36.03</td>
    </tr>
  </tbody>
  <tbody id="group-of-rows-1" class="collapse">
    <tr>
      <td></td>
      <td align="center">Campo / Carpa</td>
      <td></td>
      <td align="center">0.40</td>
    </tr>
    <tr>
      <td></td>
      <td align="center">No hay stock</td>
      <td></td>
      <td align="center">7.69</td>
    </tr>
    <tr class="clickable" data-toggle="collapse" data-target=".group-of-cau-1">
      <td></td>
      <td align="center">Se encuentra en otro lugar exhibido</td>
      <td></td>
      <td align="center">25.51</td>
    </tr>
    <tr class="group-of-cau-1 collapse">
      <td></td>
      <td>Solucionado</td>
      <td>data 1</td>
      <td>data 1</td>
    </tr>
    <tr class="group-of-cau-1 collapse">
      <td></td>
      <td>No Solucionado</td>
      <td>data 1</td>
      <td>data 1</td>
    </tr>
  </tbody>
  <tbody>
    <tr class="clickable" data-toggle="collapse" data-target="#group-of-cau-2">
      <td></td>
      <td align="center">Stock en almacén</td>
      <td></td>
      <td align="center">2.43</td>
    </tr>
  </tbody>
  <tbody id="group-of-cau-2" class="collapse">
    <tr>
      <td></td>
      <td>Solucionado</td>
      <td>data 1</td>
      <td>data 1</td>
    </tr>
    <tr>
      <td></td>
      <td>No Solucionado</td>
      <td>data 1</td>
      <td>data 1</td>
    </tr>
  </tbody>
</table>

</body>
</html>